# Form implementation generated from reading ui file 'C:\Users\Professional\Desktop\Diplom\UI_Files\Login_UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setFixedSize(458, 339)
        font = QtGui.QFont()
        font.setBold(True)
        LoginWindow.setFont(font)
        LoginWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        LoginWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Professional\\Desktop\\Diplom\\UI_Files\\../../Downloads/RegPhoto.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        LoginWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        font = QtGui.QFont()
        font.setBold(False)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 239, 441, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LoginButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.LoginButton.setObjectName("LoginButton")
        self.verticalLayout.addWidget(self.LoginButton)
        self.RegistrationButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.RegistrationButton.setObjectName("RegistrationButton")
        self.verticalLayout.addWidget(self.RegistrationButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 90, 271, 116))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoginLable = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.LoginLable.setFont(font)
        self.LoginLable.setObjectName("LoginLable")
        self.verticalLayout_2.addWidget(self.LoginLable)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.PasswordLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.verticalLayout_2.addWidget(self.PasswordLabel)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.ForgotLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.ForgotLabel.setFont(font)
        self.ForgotLabel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ForgotLabel.setObjectName("ForgotLabel")
        self.verticalLayout_2.addWidget(self.ForgotLabel)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 22))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Регистрация"))
        self.LoginButton.setText(_translate("LoginWindow", "Войти"))
        self.RegistrationButton.setText(_translate("LoginWindow", "Зарегистрироваться"))
        self.LoginLable.setText(_translate("LoginWindow", "Логин"))
        self.PasswordLabel.setText(_translate("LoginWindow", "Пароль"))
        self.ForgotLabel.setText(_translate("LoginWindow", "Забыли пароль?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec())
