# Form implementation generated from reading ui file 'C:\Users\Professional\Desktop\Diplom\UI_Files\Registration_UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(458, 339)
        font = QtGui.QFont()
        font.setBold(True)
        RegistrationWindow.setFont(font)
        RegistrationWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        RegistrationWindow.setMouseTracking(False)
        icon = QtGui.QIcon.fromTheme("contact-new")
        RegistrationWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=RegistrationWindow)
        font = QtGui.QFont()
        font.setBold(False)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 240, 441, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RegistrationButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.RegistrationButton.setObjectName("RegistrationButton")
        self.verticalLayout.addWidget(self.RegistrationButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 50, 301, 143))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoginLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setObjectName("LoginLabel")
        self.verticalLayout_2.addWidget(self.LoginLabel)
        self.LoginLineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.LoginLineEdit.setObjectName("LoginLineEdit")
        self.verticalLayout_2.addWidget(self.LoginLineEdit)
        self.Password_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.Password_label.setFont(font)
        self.Password_label.setObjectName("Password_label")
        self.verticalLayout_2.addWidget(self.Password_label)
        self.PasswordLineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout_2.addWidget(self.PasswordLineEdit)
        self.PositionLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.PositionLabel.setFont(font)
        self.PositionLabel.setObjectName("PositionLabel")
        self.verticalLayout_2.addWidget(self.PositionLabel)
        self.PositionComboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget_2)
        self.PositionComboBox.setObjectName("PositionComboBox")
        self.verticalLayout_2.addWidget(self.PositionComboBox)
        RegistrationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=RegistrationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 22))
        self.menubar.setObjectName("menubar")
        RegistrationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=RegistrationWindow)
        self.statusbar.setObjectName("statusbar")
        RegistrationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("LoginWindow", "Регистрация"))
        self.RegistrationButton.setText(_translate("LoginWindow", "Зарегистрироваться"))
        self.LoginLabel.setText(_translate("LoginWindow", "Логин"))
        self.Password_label.setText(_translate("LoginWindow", "Пароль"))
        self.PositionLabel.setText(_translate("LoginWindow", "Должность"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationWindow = QtWidgets.QMainWindow()
    ui = Ui_RegistrationWindow()
    ui.setupUi(RegistrationWindow)
    RegistrationWindow.show()
    sys.exit(app.exec())
